import type { Metadata } from 'next';
import { Poppins, Prata } from 'next/font/google';

import './globals.css';

import { QueryProvider } from '@/libs/QueryProvider';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

const prata = Prata({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-prata',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${poppins.variable} ${prata.variable}`}>
          {children}
        </body>
      </html>
    </QueryProvider>
  );
}
